# Generated by Django 6.0.6 on 2026-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='mobile_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
