# Generated by Django 6.0.6 on 2026-09-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankbackend', '0002_customerdetails_mobile_no_customerdetails_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
