# Generated by Django 6.0.6 on 2026-09-10 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankbackend', '0003_remove_transactions_customer_delete_customerdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('acc_type', models.CharField(max_length=100)),
                ('acc_number', models.CharField(max_length=100)),
                ('acc_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('trans_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trans_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankbackend.customerdetails')),
            ],
        ),
    ]
