# Generated by Django 6.0.6 on 2026-09-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbackend', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='trans_id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
