# Generated by Django 6.0.6 on 2026-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbackend', '0005_remove_transactions_trans_id_transactions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='customer_acc_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
