# Generated by Django 6.0.6 on 2026-09-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbackend', '0006_transactions_customer_acc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
