# Generated by Django 6.0.6 on 2026-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbackend', '0008_remove_transactions_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
