# Generated by Django 6.0.6 on 2026-09-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbackend', '0009_transactions_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='acc_balance',
            new_name='closing_balance',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='closing_balance',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='opening_balance',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
