# Generated by Django 6.0.6 on 2026-09-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankbackend', '0010_rename_acc_balance_customerdetails_closing_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='closing_balance',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='opening_balance',
        ),
    ]
