# Generated by Django 6.0.6 on 2026-09-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbackend', '0011_remove_customerdetails_closing_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='acc_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
